### ISSUE TITLE
Missing libfabric?

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#1]
I've previously built a prerelease version of the SDK using Visual Studio 2019 and the `rmt_proj.sln` solution file in the `proj` folder. However, the `libfabric` project is no longer included and it now fails to compile. Is this an oversight or is there a step that I missed and it's now necessary to download the source code for this library separately? I notice that the Windows Installation Guide mentions downloading and building the AWS SDK for C++, which I had not previously needed. I briefly looked at its source and did not see any mention of libfabric, but I could have missed it.

**Comment by danengholm** [comment]
I admit that the documentation may be a little confusing. The Note: right under "Install the AWS CDI SDK" in the Windows install guide refers to the Linux install guide for getting the libfabric source code. We now direct you to clone it directly from its official GitHub repository rather than providing it with the AWS CDI SDK as we did before.

**Comment by f2bo** [comment]
Yes, I did miss it. Sorry.

It would be clearer if this was a required step instead of a note, similar to the PDCurses step below. It would also be helpful to include a note explaining why the AWS SDK for C++ is needed. Is it only required to enable CloudWatch?

Thanks!

**Comment by danengholm** [comment]
We have an action item to update the documentation to make the instructions clearer.

The AWS SDK is a requirement for two pieces of functionality. The first is if you want to publish metrics to CloudWatch in your own account. The second is for AWS to gather performance metrics on CDI​.

**Comment by f2bo** [comment]
Good. Thanks!
