### ISSUE TITLE
Crash if a connection cannot be opened

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#10]
There seems to be a problem shutting down a connection if the connection couldn't be opened in the first place, for example, if the selected port is already in use.

Following the execution path starting from the `RxCreateInternal` method, whenever the call to `CdiAdapterCreateConnection` returns with an error, it fails to initialize `con_state_ptr->adapter_connection_ptr`.

https://github.com/aws/aws-cdi-sdk/blob/f62051a842f33b005280075327cc0c8241042aba/src/cdi/internal_rx.c#L826-L828

However, further down in the same method, it calls `ConnectionDestroyInternal` passing in the `con_state_ptr` parameter.

https://github.com/aws/aws-cdi-sdk/blob/f62051a842f33b005280075327cc0c8241042aba/src/cdi/internal_rx.c#L841-L844

Eventually, execution reaches `EndpointManagerShutdownConnection` where the uninitialized `adapter_connection_ptr` is used and results in a crash.

https://github.com/aws/aws-cdi-sdk/blob/f62051a842f33b005280075327cc0c8241042aba/src/cdi/endpoint_manager.c#L603-L604

This can be reproduced with the `cdi_test_min_rx` **running in the debugger** and specifying a port number already in use.

**Comment by mhhen** [comment]
Fernado,

The crash has been recently resolved and changes have been pushed to mainline. See:
https://github.com/aws/aws-cdi-sdk/blob/4fb2654cef8c5527eab36891fffc6388720839c8/src/cdi/endpoint_manager.c#L605
