### ISSUE TITLE
Build problem - AWS CDI SDK Makefile looking for /aws-sdk-cpp/aws-cpp-sdk-core

### ISSUE THREAD

**Issue by t11s** [aws/aws-cdi-sdk#103]
```
$ make DEBUG=y AWS_SDK=../aws-sdk-cpp/
Makefile:309: *** AWS_SDK does not point to the root of the AWS SDK..  Stop.

$ ls ../aws-sdk-cpp
attribution     CODE_OF_CONDUCT.md  doc_crosslinks      LICENSE                     README.md   tools
CHANGELOG.md    CONTRIBUTING.md     doc_crosslinks_new  LICENSE.txt                 src
cmake           crt                 docs                NOTICE.txt                  tests
CMakeLists.txt  cspell.json         generated           prefetch_crt_dependency.sh  toolchains
```

In Makefile:
`            ifeq (0,$(shell if [ -d $(AWS_SDK_ABS)/aws-cpp-sdk-core ]; then echo 1; else echo 0; fi))
                $(error AWS_SDK does not point to the root of the AWS SDK.)`

The docs state:

> AWS SDK C++ will be compiled during the build process of AWS CDI SDK, so it is only necessary to download it.

Instead of documented:

`make DEBUG=y AWS_SDK=../aws-sdk-cpp/`

I tried:

`make DEBUG=y AWS_SDK=../aws-sdk-cpp/src/`

which started the make process, but ended with:

```
make: *** No rule to make target `/home/ec2-user/cdi/aws-cdi-sdk/build/debug/include/aws/core/Aws.h', needed by `/home/ec2-user/cdi/aws-cdi-sdk/build/debug/obj/cloudwatch_sdk_metrics.o'.  Stop.
```

**Comment by mhhen** [comment]
Thank you for identifying this issue. There were recent changes to the AWS SDK CPP that caused this problem to occur. See changes [here](https://github.com/aws/aws-sdk-cpp/commit/7150f318cccad0048383c6a6fb5aaf886aaf1589). We will push changes to the developer_preview branch that resolve the problem for both Linux and Windows variants.

**Comment by mhhen** [comment]
See changes to [developer_preview](https://github.com/aws/aws-cdi-sdk/commit/aff323461b571202f97accf0cadb8c9088abc865) branch.

**Comment by llamafilm** [comment]
I found this same error today, trying to build on Rocky linux 8.7 with the latest mainline.  Switching to developer_preview branch fixed it.
