### ISSUE TITLE
cdi_test --stats_cloudwatch fails with 0 arguments

### ISSUE THREAD

**Issue by mjnowen** [aws/aws-cdi-sdk#105]
Contrary to what the CDI-SDK docs & ``./build/debug/bin/cdi_test --help_stats`` indicate, when the ``--stats_cloudwatch`` argument is used with ``cdi_test`` with 0 arguments, it fails instead of using the default values as per the [documentation](https://github.com/aws/aws-cdi-sdk/blob/mainline/USER_GUIDE_TEST_APP.md#using-aws-cloudwatch-with-cdi):

$ ./build/debug/bin/cdi_test --help_stats

```
To enable CloudWatch use the global --stats_cloudwatch option. Choices for each argument:
  <namespace>            - Name of CloudWatch namespace. If "NULL", "CloudDigitalInterface" is used.
  <region>               - Name of CloudWatch region. If "NULL", region where test is
                           running is used.
  <dimension domain>     - Name of CloudWatch dimension called "Domain".
```

> The namespace controls the naming of the overall metrics container. **This value defaults to CloudDigitalInterface if AWS CloudWatch is enabled and the namespace is unspecified.**
> The region specifies the location to send the metrics, eg. us-west-2. **If this value is unspecified, it defaults to the region in which the SDK is running.**
> The dimension domain provides a unique name/value pair for the metric. **The domain defaults to the connection name.**

Steps to reproduce:

```
ubuntu@transmitter:~/build/aws-cdi-sdk$ ./build/debug/bin/cdi_test --adapter EFA --local_ip 172.31.1.228 --stats_cloudwatch -X --remote_ip 172.31.1.170 --connection_name small_xfer --tx RAW --dest_port 2000 --rate 60 --num_transactions 100 -S --payload_size 5184000 --pattern INC --stats_period 1
Got option [-X] when expecting argument to option [--stats_cloudwatch].
Read-only Settings:
   tx_retry_timeout_ms : 20000
   rx_wait_timeout_ms  : 20000

ubuntu@transmitter:~/build/aws-cdi-sdk$ ./build/debug/bin/cdi_test --adapter EFA --local_ip 172.31.1.228 -X --remote_ip 172.31.1.170 --connection_name small_xfer --tx RAW --dest_port 2000 --rate 60 --num_transactions 100 -S --payload_size 5184000 --pattern INC --stats_period 1 --stats_cloudwatch
ERROR: Option [--stats_cloudwatch] requires [3] arguments.
Read-only Settings:
   tx_retry_timeout_ms : 20000
   rx_wait_timeout_ms  : 20000
```

**Comment by ctrammer** [comment]
Thanks for letting us know about this issue.

We've improved the documentation to correctly describe the format of the `--stats_cloudwatch` option. Specifically, all 3 arguments must be provided. The fallback values can be used by passing the literal string `NULL` for the namespace or region fields.

This [commit](https://github.com/aws/aws-cdi-sdk/commit/435cf7d783ef374b1243612ccaf61a9e003755ce) updates the user guide to reflect this.
