### ISSUE TITLE
Handling multiple streams using the same connection

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#11]
The pre-release SDK included several specific functions for handling streams `RmtAvmTxCreateStreamConnection` / `RmtAvmTxCreateStreamEndpoint` / `RmtAvmStreamEndpointDestroy`. For this release, the first two methods appear to have been dropped but strangely `CdiAvmStreamEndpointDestroy` still exists in the public API. Also, the comments mention a "CdiAvmTxCreateStream() API" which I cannot find.

https://github.com/aws/aws-cdi-sdk/blob/90074c5820c86b444fac2276452f654d67d467f8/include/cdi_avm_api.h#L230-L237

There are also some functions that appear to be related but these are not public.

https://github.com/aws/aws-cdi-sdk/blob/90074c5820c86b444fac2276452f654d67d467f8/src/cdi/internal_tx.h#L46-L52

On the other hand, `CdiAvmTxPayloadConfig` and the argument to the receiver callback parameter `CdiAvmRxCbData` both include a `CdiAvmExtraData` member with a `stream_identifier` field.

https://github.com/aws/aws-cdi-sdk/blob/90074c5820c86b444fac2276452f654d67d467f8/include/cdi_avm_api.h#L106-L111

However, it seems that the `cdi_test` application, which previously used RmtAvmTxCreateStreamEndpoint, not only sets `avm_extra_data.stream_identifier`

https://github.com/aws/aws-cdi-sdk/blob/f62051a842f33b005280075327cc0c8241042aba/src/test/test_transmitter.c#L276-L277

but it also encodes the stream identifier inside the user-defined data sent with each payload. 

https://github.com/aws/aws-cdi-sdk/blob/f62051a842f33b005280075327cc0c8241042aba/src/test/test_transmitter.c#L247-L252

I'm a bit confused. What is the recommended approach for handling multiple streams using the same connection?

Thanks

**Comment by mhhen** [comment]
Fernando, the pre-release SDK will contain functionality to support multiple streams using the same connection. However, the current version does not include all of the required changes to support it.

The new public APIs will be: CdiAvmTxStreamConnectionCreate(), CdiAvmTxStreamEndpointCreate() and CdiAvmTxStreamEndpointDestroy().

"CdiAvmTxCreateStream" will be called "CdiAvmTxStreamEndpointCreate".

The internal functions called TxCreateStreamConnectionInternal() and TxCreateStreamEndpointInternal() will be used by the new public APIs.

The "stream_identifier" field is used to identify each stream within a single connection. The test application also uses it as part of the user-defined data to help with payload validation (only used for test purposes). Updated diagrams and documentation will be provided as part of additional changes made to this branch.

We will leave this ticket open until the changes are pushed to the branch.

**Comment by f2bo** [comment]
Hi Mike,

Just to be sure I understand correctly. Today, it would seem that sending both audio and video payloads using the same connection should be possible provided you use different stream identifiers for each type of payload. Nevertheless, you mention that not all the necessary support is currently included in the SDK. So is this something that shouldn't be attempted? What other functionality will the new stream API provide once it becomes available that prevents it from working today?

Or if you prefer, what would you recommend for sending both audio and video streams with the current API  **today**. Two separate connections?

If that's the case, I should mention that in addition to the issue reported previously when opening a single connection, which you confirmed was specific to Windows (see https://github.com/aws/aws-cdi-sdk/issues/6), I find that opening two simultaneous connections successfully is extremely difficult, to put it mildly, at least on a Windows development machine. I'm not sure whether this is a different manifestation of the same underlying cause as the other issue but when you do this, the application **very frequently** fails with the following assertion:

https://github.com/aws/aws-cdi-sdk/blob/90074c5820c86b444fac2276452f654d67d467f8/src/cdi/adapter_efa.c#L276

(ret here is -22, if that helps)

Restarting the app several times eventually allows both connections to succeed but it's very painful to have do this every time.

Thanks

**Comment by mhhen** [comment]
Fernando,

The release and current pre-release versions of the SDK support sending multiple payload types using the same connection. Each payload type must use unique stream identifiers as you pointed out. There are no requirements that audio and video streams must use separate connections with either version of the SDK.

The additional feature that will be added to the pre-release branch contains the new stream APIs that I commented on previously, which support muxing and demuxing of streams using multiple endpoints. The new APIs allow a transmitter to use a single connection that contains multiple streams of different payload types, demux them and send to different endpoints. A receiver can receive multiple streams of different payload types from different endpoints and mux them together using a single connection.

Please refer to this diagram as an example of both mux/demux flows:
https://github.com/aws/aws-cdi-sdk/blob/avm-2.0-preview/doc/multi_endpoints_flow.jpg

We are continuing to work on resolving the issues with multiple connections, that affect windows and in some cases Linux. We will update this ticket with new information as we progress.

**Comment by f2bo** [comment]
Hi Mike,

Glad to hear that there shouldn't be any problems sending multiple payload types using the same connection as this is the path I've been currently pursuing given the issues I'm experiencing with multiple connections. The muxing and demuxing sounds really interesting. Looking forward to that.

Thanks!

**Comment by mhhen** [comment]
Since the last update to this issue, several improvements and bug fixes related to multiple connections have been published. In addition, we have completed the work on the new APIs, but are not ready to publish them yet (still reviewing code changes and testing). We will update this ticket again when the new APIs become available.

**Comment by mhhen** [comment]
We have published the changes in [Release 2.2.0](https://github.com/aws/aws-cdi-sdk/releases/tag/Release_2.2.0).
