### ISSUE TITLE
CDI 3.0.0 on Windows compile issues

### ISSUE THREAD

**Issue by dessatel** [aws/aws-cdi-sdk#113]
Something is still broken in either  cdi_proj.sln project files for CDI 3.0 or libfabric_new project files.

This part of README:
In the libfabric_new folder, rename the **libfabric**.vcxproj, **libfabric_new**.vcxproj.filters and **libfabric_new**.vcxproj.user files to use libfabric_new instead of libfabric. This is done for several reasons. The AWS CDI SDK solution file uses them as a project source and linking to the generated libraries. It also provides a clear identification of the libfabric versions while using the AWS CDI SDK solution in Visual Studio.

**BOLD** part is probably typo?
Renaming libfabric_-> libfabric_new breaks Release compilation for cdi_proj.sln. 
We can make a copy of project file with  libfabric_new instead, but then ReleaseDLL fails ( for new api libs).
It also could be better to explicitly specify  git version for libfabric_new/libfabric for Windows build, like it was in 2.4 instead of referencing Linux, since it Linux has many other git requirements.

**Comment by dessatel** [comment]
Couple breadcrumbs for windows issue:
in cdi_proj, project view

lib_fabric.new says loads failed, on reload , project does not contain requested configuration Release|x65 
rdmawin - the project of web cannot be found

**Comment by dessatel** [comment]
opening libfaric_new in VS, and replacing Replacing Release(v142) with Release
+ adding efawin after removing rdmawin fixes the issue, at last I get through compile and running cdi_min_tx

**Comment by mhhen** [comment]
Thanks for providing some additional information and possible solution to the compile problem. Not sure what happened, but the correct solution file did not get pushed to GitHub. I pushed some [changes](https://github.com/aws/aws-cdi-sdk/commit/9f225864ff830b06f725327bab2a32bd112fc9e1) to the developer_preview branch that should fix the build issues. Still testing and I will update this issue with final findings.

**Comment by mhhen** [comment]
I just pushed changes to the developer_preview branch with [this commit](https://github.com/aws/aws-cdi-sdk/commit/a63a266fd13390383e58666853a50af047ac6d63). Libfabric v1.15.2 is required in order to use the EFA adapter. There are some issues still being resolved with later versions of libfabric and use of the EFA adapter.
