### ISSUE TITLE
Incorrect libfabric version

### ISSUE THREAD

**Issue by llamafilm** [aws/aws-cdi-sdk#117]
I tried following the developer_preview build instructions on Rocky Linux 8.7 and got this error:
```
/home/nfsuper/cdi_build/aws-cdi-sdk/include/cdi_os_api.h:289:47: error: negative width in bit-field ‘__error_if_negative’
 #define CDI_STATIC_ASSERT(condition, message) _Static_assert(condition, message) // NOTE: ACTUAL ERROR IS BELOW.
                                               ^~~~~~~~~~~~~~
/home/nfsuper/cdi_build/aws-cdi-sdk/src/libfabric_api/libfabric_api.c:45:5: note: in expansion of macro ‘CDI_STATIC_ASSERT’
     CDI_STATIC_ASSERT(FI_MAJOR_VERSION == 1 && FI_MINOR_VERSION == 15, "Incorrect libfabric version.");
     ^~~~~~~~~~~~~~~~~
make: *** [Makefile:468: /home/nfsuper/cdi_build/aws-cdi-sdk/build/release/obj/libfabric_api.o] Error 1
```

The instructions say to download libfabric 1.14.  I fixed this by downloading 1.15 instead.

**Comment by mhhen** [comment]
It looks like the mainline branch of the SDK says to use v1.14.0 of libfabric. However, the [linux install guide](https://github.com/aws/aws-cdi-sdk/blob/developer_preview/INSTALL_GUIDE_LINUX.md) of the developer_preview branch says to use v1.9.x-cdi and v1.15.2 of libfabric. Refer to the "Install AWS CDI SDK" section as shown below:

```
git clone --single-branch --branch v1.9.x-cdi https://github.com/aws/libfabric libfabric
git clone --single-branch --branch v1.15.2 https://github.com/ofiwg/libfabric libfabric_new
```

We plan on merging all the changes on the developer_preview branch to mainline and publishing a new release of the SDK by the end of this month. Please let us know if there are any other documentation issues.
