### ISSUE TITLE
How to use RGB test file source?

### ISSUE THREAD

**Issue by llamafilm** [aws/aws-cdi-sdk#119]
Could you please provide an example of how to use `cdi_test` with RGB video encoding?  I have successfully tested at 4:2:2 using the following command, but I can't get it to work with RGB.  There are no RGB samples at https://cdi.elemental.com/test_content/index.html

```
cdi_test --adapter EFA --local_ip 10.128.33.42 -X --tx AVM --remote_ip 10.128.32.65 --dest_port 5000 \
--rate 24 -S --id 0 \
--payload_size 5184000 \
--file_read ~/CDI/Color_Bars_1080P_422_10bit.yuv \
--avm_video 1920 1080 YCbCr422 Unused 10bit 24 1 BT2020 false false PQ Narrow 16 9 0 1080 0 0
```

I tried creating the raw RGB test file with ffmpeg like this:
```
ffmpeg -i PQ_color_bars_HD.tif -f rawvideo -pix_fmt gbrp10le PQ_color_bars_HD.rgb
```
That produces a file with size 12441600 Bytes (6 Bytes per pixel) which doesn't make sense to me.  I would expect 10-bit RGB to be 7776000 Bytes.  Anyway, I tried `cdi_test` with RGB and payload_size= 12441600 and it doesn't complain, but the output looks scrambled.
<img width="783" alt="Screenshot 2023-06-05 at 3 03 13 PM" src="https://github.com/aws/aws-cdi-sdk/assets/3991046/8220914f-c877-4bed-a7d1-0568c56cb5ed">

**Comment by mhhen** [comment]
Thank your for providing the level of detail for this issue. 10-bit RGB in CDI uses the Linear RGB format defined in SMPTE 2110-20 which transmits each 4 pixel pgroup in 15 octets. For a 1920x1080 picture, this results in a payload size of 7,776,000 bytes, as you are expecting. This pixel format does not appear to be supported by open source tools such as ffmpeg. Can you unzip the attached file SMPTE_Color_Bars_16x9.rgb10 and try it to see if this works correctly for you? The size of the file is 7,776,000 bytes.

Use your cdi_test command line but replace YcbCr422 with RGB, set payload_size to 7776000 and use the new filename for the --file_read option.

[SMPTE_Color_Bars_16x9.zip](https://github.com/aws/aws-cdi-sdk/files/11682354/SMPTE_Color_Bars_16x9.zip)

**Comment by llamafilm** [comment]
Thank you, that works.
I'm curious if you're able to share what tool can be used to create such a file?

**Comment by jbielman-aws** [comment]
We have uploaded a script that creates the binary 10-bit RGB file to the developer_preview branch along with instructions [here](https://github.com/aws/aws-cdi-sdk/commit/a52abc67eed2c9f34d2d869db7835b4d9c7533bf). Resolving this issue, but let us know if you encounter any further issues with your testing. Thank you for verifying that the test file works correctly.

**Comment by jbielman-aws** [comment]
We have also uploaded this test content to the CDI Test Content page [here](https://cdi.elemental.com/test_content/index.html).
