### ISSUE TITLE
Setting tx_buffer_size_bytes to more than 2GB returns error. 

### ISSUE THREAD

**Issue by kazkam1981** [aws/aws-cdi-sdk#120]
I am calling `CdiCoreNetworkAdapterInitialize` to allocate more than 2GB and it returns an error that the allocation failed. 
i think the problem is with int overflow for more than 2GB. i have [forked](https://github.com/kazkam1981/aws-cdi-sdk/) the repo and created two branches with my fix:

1. Out of 2.4.1 commit: https://github.com/kazkam1981/aws-cdi-sdk/tree/intTo64tag24 
2. Out of mainline: https://github.com/kazkam1981/aws-cdi-sdk/tree/cdi3intToint64

They are essentially the same. i have tested the first one on an EC2 instance allocating 8GB and 16 GB and it worked.

**Comment by mhhen** [comment]
Changes to support this feature have been pushed to the developer_preview branch. See [commit](https://github.com/aws/aws-cdi-sdk/commit/e555fd07188ba1cf014bf098d3f58f4abe6db844) and [commit](https://github.com/aws/aws-cdi-sdk/commit/95bf2cdd9b53eb0f94c26c542976831d511d4e3e).
