### ISSUE TITLE
CDI3.0. Complex stacks fails in fi_sendmsg()

### ISSUE THREAD

**Issue by kazkam1981** [aws/aws-cdi-sdk#121]
In testing CDI3.0 we come across this error in some cases: 
`Got [-11 (Resource temporarily unavailable)] from fi_sendmsg(), tried [5] times.`

The test in question can be summarized in these steps:

- First we make a call to `CdiCoreNetworkAdapterInitialize`  with a `CdiAdapterData` that has `tx_buffer_size_bytes`  set to 4GB (4000 * 1024 * 1024).

- We take this allocated memory and create a circular buffer out of it.

- In this stack there are 5 remotes: So we make 5 calls to `CdiRawTxCreate` .

- There are 21 video renditions distributed across 5 remotes. For example you can see that the last remote in this stack has 6 (video_hevc_main10_1920x1080_1500 etc.)

- For each of these 21 renditions there is an agent on the Boss instance that allocate buffer from the circular buffer and eventually calls `CdiRawTxPayload` .

- So you can imagine that in this example there are 21 of these agents that try to allocate buffer from this pool and send them to CDI.

- Each of these agent has a queue that track allocated buffers and release the buffer when the send callback is received from CDI.

- The length of these queues could reach to 40 sometimes. 

- With 4GB of allocated memory we see no problems with CDI 2.4.

Now the size of these buffers depend on the renditions for 4k the max is `24 MB` for non-4ks it can be much less under `1MB `e.g.

**Two observations:**

1. Increasing the [max_num_retries](https://code.amazon.com/packages/Krill_SDK/blobs/8bf0ff27871010c38c67db30a0ab206c3861bd2b/--/src/cdi/adapter_efa_tx.c#L93) from 5 to 50 didn't help.
2. If a certain delay is addede in sending buffers to CDI then the error goes away but of course we see delay in our workflow which we can't accept.

**Comment by mhhen** [comment]
2. The delay added above was 100 ms when the length of the queue of buffers not sent yet exceeds 35 e.g.

**Comment by mhhen** [comment]
The problem was caused by a change that was made in the newer version of libfabric. Changes to fix the problem have been pushed to the developer_preview branch as part of this [commit](https://github.com/aws/aws-cdi-sdk/commit/e555fd07188ba1cf014bf098d3f58f4abe6db844).
