### ISSUE TITLE
Installation document needs revision

### ISSUE THREAD

**Issue by dcrearer** [aws/aws-cdi-sdk#19]
Installation of gcc is needed before build CMake 3.15 from source. Otherwise bootstrap fails.

Documentation should be updated to use the following order:

`sudo yum -y install gcc-c++ make libnl3-devel autoconf automake libtool doxygen ncurses-devel
<img width="1165" alt="Screen Shot 2020-11-25 at 11 31 27 PM" src="https://user-images.githubusercontent.com/6692259/100308415-5abe4f00-2f76-11eb-8ea7-044ce182d548.png">
`

```
cd
wget https://github.com/Kitware/CMake/releases/download/v3.15.3/cmake-3.15.3.tar.gz
tar -zxvf cmake-3.15.3.tar.gz
cd cmake-3.15.3
./bootstrap --prefix=/usr/local
make
sudo make install
```

**Comment by trevorheaws** [comment]
Thank you for bringing this issue to our attention. We have merged commit 3c5ce7bf3db747d5cd23ff56fa18fee250be1167 to update the documentation.
