### ISSUE TITLE
Can't visit CDI specs

### ISSUE THREAD

**Issue by kierank** [aws/aws-cdi-sdk#3]
https://cdi.elemental.com/specs/baseline-video reports an error

**Comment by danengholm** [comment]
Kieran,
Thank you for reporting this. We are aware of the problem.
These URIs serve a dual purpose. The most important one is that it is a globally unique identifier used to unambiguously reference a specification in the SDK's AVM interface. These URIs are owned by AWS and managed such that they meet the requirements set out in the documentation. As a bonus, they can also refer directly to said documents so people can see the details of the specification that claims the URI as its own. The text is in files in the docs/specs directory in the aws-cdi-sdk project; the URLs in question are aliases to those files.
We do intend to fix this soon but it is not considered our highest priority at the moment.

**Comment by mhhen** [comment]
We are re-opening this issue and will update/close it after the problem has been resolved.

**Comment by mhhen** [comment]
The links to the specifications are now working, so we are closing this issue.
