### ISSUE TITLE
Unbalanced call to WSACleanup in CdiCoreShutdown

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#30]
In Windows, if `CdiCoreShutdown` is called without opening a connection, it's currently possible for `WSACleanup` to be called without a corresponding invocation of `WSAStartUp`. This is because `CdiOsShutdown` invokes it regardless of the state of the variable `winsock_initialized`.

https://github.com/aws/aws-cdi-sdk/blob/3e81593b7cab6e6f1f8c4b2d564e82364dd9d3f4/src/common/src/os_windows.c#L1307-L1311

While this should be rare in most scenarios and would probably go unnoticed, it can happen when `CdiCoreShutdown` is called without having opened any CDI connections. For example:

```
CdiReturnStatus rs = CdiCoreInitialize(&core_config);

if (some_condition_that_is_not_fulfilled) {
   // code to open a CDI connection never executes
}

rs = CdiCoreShutdown();
```

This causes problems for applications that need to open sockets unrelated to CDI and have already called `WSAStartUp`. For example, I'm currently having this problem executing functional tests that execute CDI code in Visual Studio (with MSTEST), which uses sockets to retrieve results from the test host. If one of the tests calls `CdiCoreInitialize`/`CdiCoreShutdown` without opening a connection, the test run fails with the following message:

```
The active test run was aborted. Reason: Test host process crashed.
```

Changing `CdiOsShutdown` to check `winsock_initialized` before calling `WSACleanup` would seem an easy way to avoid this problem.

```C
void CdiOsShutdown()
{
    if (winsock_initialized) {
        WSACleanup();
        winsock_initialized = false;
    }
}
```

**Comment by trevorheaws** [comment]
Fernando, thank you for providing the detailed description and a possible solution. This unbalanced call has been fixed in the latest commit (https://github.com/aws/aws-cdi-sdk/commit/76cc03c7b13692d28d70d01c7a07426958e2a1df) to the developer_preview branch.

**Comment by f2bo** [comment]
Thanks!
