### ISSUE TITLE
Multiple calls to CdiCoreInitialize() introduce handle/memory leaks.

### ISSUE THREAD

**Issue by yanniel** [aws/aws-cdi-sdk#34]
The CDI SDK keeps global state in the fields of the struct:

`extern CdiGlobalContext cdi_global_context;`

**CdiCoreInitialize()** allocates various types of handles that are de-allocated during **CdiCoreShutdown()**.

Subsequent calls to **CdiCoreInitialize()** without a matching (symmetrical) **CdiCoreShutdown()** will introduce handle leaks. An unsuspecting consumer of the SDK won’t know because the **CdiCoreInitialize()** returns **kCdiStatusOk** with subsequent back to back invocations.

One suggestion to prevent this: SDK’s typically keep a reference-counting-like mechanism to prevent situations like this from inadvertently happening. **CdiCoreInitialize()** could initialize the global state once (when the counter was zero) and then subsequent invocations to **CdiCoreInitialize()** would just increment the counter. Calls to **CdiCoreShutdown()** would decrease the counter and only when it goes to zero should the real shutdown begin.

**Comment by mhhen** [comment]
Thank you for identifying the problem with core global state data, and providing a suggested solution. We have taken a closer look into this area and also found a few problems with how state data in the logger was being handled. We will update this issue with additional information and/or reference to new code as work progresses.

**Comment by mhhen** [comment]
Changes that should resolve this problem have been pushed to the developer_preview branch on commit [33e66a3](https://github.com/aws/aws-cdi-sdk/commit/7e370a5af6abacaf7566dbf3fa310d12833e66a3). See important changes to [RELEASE_NOTES](https://github.com/aws/aws-cdi-sdk/commit/7e370a5af6abacaf7566dbf3fa310d12833e66a3#diff-9fbfac5aba9b4f62631e81c73b400210bf31c31da365fee4993b982f746b8e3f).

Please let us know if this resolves the issue or provide additional details if it does not.

**Comment by yanniel** [comment]
Thanks @mhhen . Just reviewed  commit 33e66a3 and I think the leak is addressed. I do have a suggestion however: instead of relying on the **sdk_initialized** flag, I suggest a reference counter whenever CdiCoreInitialize() and CdiCoreShutdown() are called (similarly to what was done in the Logger) .

**Comment by mhhen** [comment]
Good to hear that the leak has been resolved. We did discuss your suggestion and have decided to use a reference counter for CdiCoreIntialize()/CdiCoreShutdown(). This ticket will be updated as work progresses.

**Comment by yanniel** [comment]
@mhhen . Thanks for taking the time to discuss and consider adding the reference counter to the SDK. You might have noticed I suggested adding another reference counter to the network adapter (https://github.com/aws/aws-cdi-sdk/issues/36#issuecomment-775350531). I wanted to explain in more details the rationale for my suggestions.

What I am suggesting can be implemented at the application layer. This is actually what we have done within our application. That said, I think implementing this functionality within the SDK would make it easier to integrate and robust.

Context: our application is fairly dynamic. Transmitters and Receivers can be instantiated and teared down on demand. The SDK itself can be initialized and shutdown on demand. We'd like the granularity to initialize/shutdown individual network adapters in a theoretical use case where there could be more than one. 

We wanted a **simple** mechanism to ensure an adapter is not shutdown while being used by at least one TX or RX. Similarly, we wanted to ensure the SDK itself is not shutdown while there is one adapter (or for that matter an RX or TX) using it. We wanted to remove (a better word is probably "encapsulate") the "shutdown-ordering" concern from the application.

Key to this design is the word **simple**. We wanted to make all this as simple as possible, requiring as little code as possible in the application.

We have an SDK Wrapper class encapsulating the global SDK state and the calls to CdiCoreIntialize()/CdiCoreShutdown(). This class is a singleton. This SDK Wrapper has a reference counter that can be incremented/decremented by the methods below:

```
void initializeCDI(CdiCoreConfigData* core_config);
void shutdownCDI();
void initializeAdapter(String adapterID, ...otherArgs);
void shutdownAdapter(String adapterID);
```

- **initializeCDI(..)** increments the SDK reference counter. It engages the **CdiCoreIntialize(...)** when the SDK reference counter translations from zero to one. All other calls just increment the SDK reference counter. 
- **shutdownCDI()** decrements the SDK reference counter. It engages the **CdiCoreShutdown()** when the SDK reference counter goes to zero. All other calls decrement the SDK reference counter.
- **initializeAdapter(...)** creates and registers an "adapter wrapper instance" we wrote to encapsulate a CDI Network adapter. This new wrapper class has a reference counter of its own (network adapter reference counter). When **initializeAdapter()** is called, if no adapter exists yet with this  **adapterID**, then **CdiCoreNetworkAdapterInitialize()** is called, the reference counter of the adapter gets incremented but also the reference counter of the SDK is incremented. This would prevent both the SDK and the adapter in question from being shutdown while an RX or TX is alive. Key here is that there are **two** reference counters and that operations on the adapter would affect not only the reference counter of the adapter, but they will affect the reference counter of the SDK as well.
- **shutdownAdapter()** will decrement the reference counters of both the corresponding adapter and the SDK. If in the future there is an API to shutdown an individual adapter, we will call it here when the adapter reference counter goes to zero. Indirectly, if the SDK counter becomes zero as part of this call **shutdownAdapter()**, then we will call **CdiCoreShutdown** under the hood. 

All this a little hard to explain without a white board. If you feel is an undertaking worth perusing and need more details please do let me know. Thanks.

**Comment by mhhen** [comment]
Upon further review of the changes required to add reference counting to CdiCoreInitialize(), we wanted to get more of your thoughts on this topic before continuing. Since the API requires configuration data, we don't want to re-initialize the SDK every time the API is used, but only when the reference count is zero. However, what if the configuration data changes when the reference count is not zero? Suggestions/thoughts?

**Comment by yanniel** [comment]
> 
> 
> Upon further review of the changes required to add reference counting to CdiCoreInitialize(), we wanted to get more of your thoughts on this topic before continuing. Since the API requires configuration data, we don't want to re-initialize the SDK every time the API is used, but only when the reference count is zero. However, what if the configuration data changes when the reference count is not zero? Suggestions/thoughts?

@mhhen .I have my thoughts about this, but let me run it by my team. I'll be back ASAP. Thanks.

**Comment by yanniel** [comment]
@mhhen .

**Our short answer:** if the configuration data changes when the reference counter is not zero, we should fail and return an error code without incrementing the reference counter. We should not attempt to hide this from the user (hence the error code) and we would still expect symmetrical calls to **CdiCoreShutdown** for each successful calls to **CdiCoreIntialize** that previously happened. It would be up to the application to handle the error code returned by **CdiCoreIntialize** in the situation above.

Our long answer: there is not much benefit in implementing a reference counter mechanism just for the purpose of balancing calls to **CdiCoreIntialize** and **CdiCoreShutdown**. The real benefit we see comes from tracking resources (by “resources” we mainly mean the “adapters” and the “SDK itself”) already in use and preventing their shutdown while still in use by transmitters and receivers. I tried to give an idea about what we mean by this in my previous comment https://github.com/aws/aws-cdi-sdk/issues/34#issuecomment-779912279. The explanation I gave has gaps and could be iterated upon; but I hope it gives an idea. Please let me know if you want me to further discuss this topic.

If the decision is not to implement the reference counting mechanism so that it can track resources in use, then maybe a simpler solution is best: Subsequent calls to **CdiCoreIntialize** without a matching **CdiCoreShutdown** should just fail (no reference counting needed). I think the current SDK code does that.

Thanks.

**Comment by mhhen** [comment]
Yes, the current SDK code does fail as expected (no reference counting needed).

We have decided not to use reference counting in **CdiCoreIntialize** and **CdiCoreShutdown**.  See changes made to issue #36 that should also address this issue.

**Comment by yanniel** [comment]
@mhhen. Based on your last comment I don't think there's anything outstanding for this issue. Is there?

**Comment by mhhen** [comment]
Correct, and thanks for the clarification. We will close the ticket.
