### ISSUE TITLE
Unbalanced CdiCoreNetworkAdapterInitialize()

### ISSUE THREAD

**Issue by yanniel** [aws/aws-cdi-sdk#36]
“Adapter resources” (ex. TX adapter buffers used to transmit payloads) are allocated during **CdiCoreNetworkAdapterInitialize()**. It would be beneficial to have a matching _CdiCoreNetworkAdapter**Un**initialize()_ that could de-allocate the adapter resources instead of having them around for the life of the application. See somewhat related case: https://github.com/aws/aws-cdi-sdk/issues/35.

This would be useful should the memory requirements of the workflow were to dynamically change.

A reference-counting-like mechanism could be used to keep CdiCoreNetworkAdapterInitialize()\CdiCoreNetworkAdapterUninitialize() balanced. See last paragraph of: https://github.com/aws/aws-cdi-sdk/issues/34.

**Comment by yanniel** [comment]
A few more details: 

**CleanupGlobalResources()** is iterating over the **cdi_global_context.adapter_handle_list** with the intent of freeing all adapters via **AdapterShutdownInternal()**.

I suggest adding an API that would allow shutting down a specific adapter. It will require calling **AdapterShutdownInternal()** on said adapter and also removing it from the **cdi_global_context.adapter_handle_list**.

The prototype of the new API would be something like this:

`CDI_INTERFACE CdiReturnStatus CdiCoreNetworkAdapterUninitialize(CdiAdapterHandle handle);`

Consider using a reference counter (even if for consistency) to keep calls to CdiCoreNetworkAdapterInitialize()\CdiCoreNetworkAdapterUninitialize() on the same adapter balanced.

**Comment by mhhen** [comment]
As part of the work and ongoing discussions for issue #34, we are planning to add the new API as you have suggested. Thanks for the excellent detail on these issues. We will update this issue as work progresses.

**Comment by yanniel** [comment]
My pleasure. Thanks for considering it.

**Comment by mhhen** [comment]
We pushed changes to the developer-preview branch (commit [85284b1](https://github.com/aws/aws-cdi-sdk/commit/84fa53bf9f5c7f0bb7576a3fe514ba6ea85284b1)) that should resolve this issue. See updated notes in [RELEASE_NOTES](https://github.com/aws/aws-cdi-sdk/commit/84fa53bf9f5c7f0bb7576a3fe514ba6ea85284b1#diff-9fbfac5aba9b4f62631e81c73b400210bf31c31da365fee4993b982f746b8e3f).

Please let us know if this resolves this issue.

**Comment by mhhen** [comment]
We are going to close this issue for now, but will reopen if you determine that it has not been resolved.

**Comment by yanniel** [comment]
@mhhen . Apologies for not getting back to this any sooner. I'll provide some feedback ASAP. Thanks.

**Comment by yanniel** [comment]
@mhhen . Just verified this works correctly. Because we don't have two physical EFA adapters we used the IPv4 of the machine for one EFA adapter and the loop-back address for the other one.  I could stop/resume an Adapter/RX/TX trio without affecting a distinct Adapter/RX/TX trio. 

Also, I glanced at the code changes done in the SDK and it seems fine. One observation: I noticed no code changes were done for the other two adapter types (sockets and libfabric).

Thanks for the effort!

**Comment by mhhen** [comment]
The other two adapter types should not require any code changes. The change that was made to the EFA adapter (see src/cdi/adapter_efa.c, in [85284b1)](https://github.com/aws/aws-cdi-sdk/commit/84fa53bf9f5c7f0bb7576a3fe514ba6ea85284b1) were to account for control_interface_adapter_handle, which only exists in the EFA adapter.

**Comment by yanniel** [comment]
Thanks for the clarification.
