### ISSUE TITLE
CdiQueueDestroy assert while the query is not empty

### ISSUE THREAD

**Issue by AlexImagineComm** [aws/aws-cdi-sdk#37]
I try to destroy Raw Receiver while the queue is not empty and call the CdiCoreConnectionDestroy(m_hConnectionHandle).
It invokes assert on the CdiQueueDestroy, because at this point the queue of the Receiver can be not empty.
Please see the attached document with the stack trace of the issue (the build is in debug mode).

 EFA Adapter type is used.

Please advice how I should invoke the CdiCoreConnectionDestroy on the Receiver side to ensure that the queue is empty. I obviously can not ensure that the Transmitter is stopped and during the stopping of the Receiver the Transmitter still sending the payloads.

[CdiQueueDestroy.question.docx](https://github.com/aws/aws-cdi-sdk/files/6051547/CdiQueueDestroy.question.docx)

Regards
Alex

**Comment by mhhen** [comment]
Alex, thank you for providing the detailed information concerning this issue. We have been able to reproduce the problem and will update this issue as work progresses.

**Comment by mhhen** [comment]
Alex, the problem has been resolved as part of upcoming changes for issue #11. We continue to test and will update both issues when they have been pushed to the developer_preview branch.

**Comment by mhhen** [comment]
We have published the changes in [Release 2.2.0](https://github.com/aws/aws-cdi-sdk/releases/tag/Release_2.2.0).
