### ISSUE TITLE
How to find performance metics in AWS Cloudwatch?

### ISSUE THREAD

**Issue by svlobanov** [aws/aws-cdi-sdk#39]
Hello, I've built&run cdi sdk&test application, everything works fine, but I can't find performance metrics (like DroppedPayloads, LatePayloads, PayloadTimeP99, etc) in AWS Cloudwatch. Could you please describe how to find these performance metrics in CloudWatch?

Configuration&build was done by INSTALL_GUIDE_LINUX.md manual. Looks like, performance metrics are being sent. If I put invalid valued to ~/.aws/credentials I can see error message when I start cdi_test app. If I put correct values to this file, I don't see any errors.

**Comment by svlobanov** [comment]
It is required to add --stats_period 60 --stats_cloudwatch ... to ./cdi_test application

**Comment by mhhen** [comment]
Sergey, you can find documentation at [user_guide](https://github.com/aws/aws-cdi-sdk/blob/mainline/USER_GUIDE_TEST_APP.md#using-aws-cloudwatch-with-cdi). How to view the metrics is described near the end of the guide.

Concerning your question about `cdi_test` command line options, the default value for `--stats_period` is 1, so specifying it is not necessary. However, the `--stats_cloudwatch` option must be specified. An example is:

`--stats_cloudwatch CDIStats us-west-2 Stream1`

The example showing the full command is in the guide referenced above. Please let us know if you are still unable to find the metrics or have other questions.
