### ISSUE TITLE
Issue with variable defined in 'cdi_os_api.h' header file

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#4]
Including the `cdi_os_api.h` header in more than one C++ file results in `one or more multiply defined symbols found` error. 

```
Error	LNK2005	"struct siginfo_t siginfo" (?siginfo@@3Usiginfo_t@@A) already defined in ...
```

https://github.com/aws/aws-cdi-sdk/blob/90074c5820c86b444fac2276452f654d67d467f8/include/cdi_os_api.h#L138

**Comment by dmmirtiaws** [comment]
Hi Fernando,
We have reproduced your issue and will include a fix for this in our next repo update.
In the mean time, the issue can be fixed by removing the variable name "siginfo" from the struct definition.

change:
    struct siginfo_t {
        long si_pid;
        long si_uid;
} siginfo;   

to:
struct siginfo_t {
        long si_pid;
        long si_uid;
};

Hope this helps move you forward.

**Comment by f2bo** [comment]
Hi Dylon

Yes. I can move forward. I had already done something similar but wanted to make you aware of the problem. 

Thanks!

**Comment by mhhen** [comment]
We will keep this issue open until the code change has been made to the repository.

**Comment by mhhen** [comment]
The code change has been made to the repository as noted above. Closing this issue.
