### ISSUE TITLE
Multiple RAW streams in one connection not supported

### ISSUE THREAD

**Issue by yanniel** [aws/aws-cdi-sdk#42]
Three concerns for your consideration:

**Concern A:**

The AVM APIs allow specifying a `stream_identifier`; but that is not available for the RAW APIs. 

When the RAW APIs are used we typically rely on encoding information in an unsigned 64 bit integer  (`payload_user_data`). So, we could use some bits to specify a **pseudo**-stream ID to be used on the RX side.

```
CdiCoreExtraData extra_data = {
		.origination_ptp_timestamp = timestamp,   // Origination timestamp to associate with the payload.
		.payload_user_data = pseudoStreamID  // User-defined data to associate with the payload
	};
```

I call it  **pseudo**StreamID because it seems to me there is no real concept of _raw streams_ and I wonder if you could shed light as to why that is. 

I think( just as with the AVM API) that having multiple raw streams is desirable for applications that might be carrying audio/video/vanc in proprietary formats. In this use case (where interoperability is not a concern), developers can decide to encapsulate those originating proprietary streams into CDI Raw Streams. This is not truly possible given that there is no such a thing as a raw stream. 

**Concern B:**

Related to the above (but maybe more on the side of the CDI delivery of Raw payloads being single threaded when in the same connection): the RX callback receiving the raw data linearizes all payloads even if coming from "different originating streams" on the TX application; this pretty much synchronizes the streams; say, if a raw stream containing video starts putting back pressure (or even blocks ) on the RX side, it will affect all other RX streams that might not be synchronous to that one.

**Concern C:**

Finally, the connection callback provides the following information:

```
/**
 * @brief A structure of this type is passed as the parameter to CdiCoreConnectionCallback(). It contains data related
 * to the status of a single connection.
 */
typedef struct {
    /// @brief Current status of the connection.
    CdiConnectionStatus status_code;

    /// @brief If the connection is not connected, this will point to a NULL terminated error message string. The memory
    /// containing the error string is allocated by the SDK and will be freed upon return from the callback function.
    /// The application needs to copy the message to its own memory before returning if it needs it to be retained.
    const char* err_msg_str;

    /// @brief Used to identify the source data stream number associated with this connection.
    int stream_identifier;

    /// @brief Used to identify the handle of the stream endpoint associated with this connection.
    CdiEndpointHandle endpoint_handle;

    /// @brief User defined connection callback parameter. For a transmitter, this value is set as part of the
    /// CdiTxConfigData data provided as a parameter to one of the Cdi...TXCreate() API functions. For a receiver, this
    /// value is set as part of the CdiRxConfigData data provided to one of the Cdi...RxCreate() API functions.
    CdiUserCbParameter connection_user_cb_param;
} CdiCoreConnectionCbData;
```

Why is the `stream_identifier `associated with a connection status data? On the Raw API this number is left as -1. In the AVM APIs a connection could have more than one stream so what value will be set on this field (1, 2, X) and what does that even mean? 

Any clarifications are most welcome.

**Comment by mhhen** [comment]
Thank you for providing detailed descriptions. Response to your concerns are listed below:

A. The RAW protocol was designed to carry RAW payloads of data. Additional payload concepts such as streams could be implemented by adding custom data to each RAW payload. Downstream applications could then parse/decode the data. As described in issue #41, we have removed `stream_identifier` from the Core RAW API.

B. Since the receiver uses a single polling thread for each connection, your concern here is correct. In order to prevent a receiving application that can block processing of a stream, each could be placed on a different connection.

C. As part of our work on issue #11 we have removed `stream_identifier` from the RAW layer. See issue #41 for more information.

Please let us know if you have any additional questions concerning this issue.

**Comment by yanniel** [comment]
Thanks for the details @mhhen .

" the receiver uses a single polling thread for each connection". Is this true also for an AVM receiver? That individual video, audio and vanc streams belonging to the same program could not be processed in parallel? I was under the impression that because the AVM layer has the concept of streams, said streams could be processed in parallel within a connection. Now I think I was mistaken, could you please point me in the right direction here?

We were trying to be conservative when creating connections. As per the documentation "Each (-connection-)should have its own core configured and the operating system should be set up to prevent other processes from being scheduled on those cores.". From the top of my mind I don't think this is possible in Windows. Given that concern, we were trying to have as little dedicated CPU cores as possible; hence we are trying to minimize the creation of connections where possible. This would allow to minimize the need for dedicated CPU-cores. 

From a "logical" standpoint it makes sense to us that streams belonging to the same "program" are "encapsulated" in a "connection", but without the ability to process them in parallel the value is not as high as we thought. We thought the multiple stream per connection was a nice feature of CDI that differs from 2110 that requires a connection per stream.

I would appreciate any light you could shed into these concerns. Thanks.

**Comment by mhhen** [comment]
For each connection (RAW or AVM), the receiver uses a single polling thread. As payloads are received by the polling thread they are reordered and then placed in a queue that is processed by another thread, see `AppCallbackPayloadThread()` in internal.c. This thread invokes the user-registered payload callback function. As part of the callback function, the application could implement logic that determines the payload's stream type and simply places it in an associated queue. Logic that processes payloads could then be performed on a unique thread associated with each queue, allowing parallel processing of the payloads. Hopefully this approach sounds reasonable and will work for you. Please update this issue if you have other concerns or questions.

**Comment by yanniel** [comment]
Your explanation is much appreciated Mike.

Instead of "parallel" processing of streams I should have said "asynchronous" processing of streams. I used the term "parallel" incorrectly earlier.

We use the approach you suggested: we have decoupled the user-registered payload callback function from the data processing by means of a queue and a working thread per RX stream. We allow for two queue implementations (to be configured depending on the workflow): a blocking queue and a lossy queue. 

With the blocking queue implementation a slower stream could cause the other one to block once the queue capacity of the faster stream is filled. With the lossy queue, packets in the fast stream could be lost when the queue is at full capacity. Only an unbounded queue implementation would allow for asynchronous data processing of these RX streams and this is of course a no-go. This is what I was referring to when I said parallel processing of streams is not supported within a connection; I really meant "asynchronous" processing of streams.

Consider the following use case: two asynchronous streams are sent from the TX application via the same connection. The data is being sent from different data producing threads on the TX application. The SDK is synchronizing these asynchronous streams and we thought that would not be the case. We thought that "synchronization" concerns if any should be left to the application.

I understand now thanks to your explanation that this is by design. So, my rambling above is just an observation and I leave it here in case is useful to others.

One final question please:

"Each (-connection-)should have its own core configured and the operating system should be set up to prevent other processes from being scheduled on those cores." --> Do you have any recommendation as to how to achieve this in Windows?

We have control over our in-house processes and threads via affinities but there are many processes out of our control (some of which we don't even know are lurking in the machine where we run our CDI application). Say, what happens if a random process decides to run in a CPU core we have declared as dedicated to a connection? We are not aware of a way to prevent this in Windows. Any suggestion is most welcome.

Thanks.

**Comment by mhhen** [comment]
Thank you for providing some additional details here on the parallel/asynchronous topic. As far as providing recommendations for scheduling threads on Windows, we have only used the default Windows scheduler. There are methods available to set thread priorities, but we have not performed any work in this area.

**Comment by yanniel** [comment]
Thanks.
