### ISSUE TITLE
Instructions on disabling statistics gathering disingenuous

### ISSUE THREAD

**Issue by firthmj** [aws/aws-cdi-sdk#47]
I appreciate that you are keen to have customers continue to be monitored, but it is disingenuous not to point out in README.md, INSTALL_GUIDE_LINUX.md and INSTALL_GUIDE_WINDOWS.md that after changing src/cdi/configuration.h the CDI library will need to be rebuilt for the change to take effect

**Comment by mhhen** [comment]
We will add some additional notes in the documentation, but it should be assumed that changing a header file requires building libraries that use it. The documentation will be updated as part of our next commit.

**Comment by mhhen** [comment]
The documentation has been updated in [Release 2.3](https://github.com/aws/aws-cdi-sdk/releases/tag/v2.3.0)
