### ISSUE TITLE
Validate the EFA environment fails on Linux

### ISSUE THREAD

**Issue by firthmj** [aws/aws-cdi-sdk#48]
I'm running on Ubuntu 18.04, with the latest EFA package (not sure how to see the version I was given, I downloaded "https://efa-installer.amazonaws.com/aws-efa-installer-latest.tar.gz" as recommended on the https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html page on 16th June)

When I get to the "Validate the EFA environment" step in the INSTALL_GUIDE_LINUX.md instructions, the validation fails with:

```
$ ./efa_test.sh 
Starting server...
Starting client...
[error] .../libfabric/util/pingpong.c:521 : ctrl/read: no data or remote connection closed
Error: fi_pingpong test returned 103.
```

(start of path replaced with `...` for privacy)

If I install the "full" version of the EFA package (so run `sudo ./efa_installer.sh -y`, instead of `sudo ./efa_installer.sh -y --minimal`), then the validation at the end of that process succeeds.

Is there some incompatibility with the latest EFA package and the libfabric version from the CDI installation instructions, or am I doing something wrong?

**Comment by firthmj** [comment]
Debugging a little more, it looks like the fi_pingpong client is aborting with that message because the fi_pingpong server is failing with the error:

```
fi_enable(): .../libfabric/util/pingpong.c:1495, ret=-12 (Cannot allocate memory)
```

(again, start of path replaced with ... for privacy)

**Comment by firthmj** [comment]
Googling found this issue listed against the general libfabric:

https://github.com/ofiwg/libfabric/issues/6437

For some reason `/etc/security/limits.d/efa.conf` had gone missing on my instance, so I could only run libfabric as root. Copying this file from a second instance I built to debug the issue has resolved my problem

**Comment by mhhen** [comment]
Thank you for providing a solution to the problem. We will add a note in the Linux install guide and reference this issue.
