### ISSUE TITLE
CdiAvmConfig.data_bytes – Video stream: width/height entries separated by comma instead of semicolon

### ISSUE THREAD

**Issue by yanniel** [aws/aws-cdi-sdk#49]
As described https://cdi.elemental.com/specs/baseline-video-vxx.yy.html "The bytes of the array are the ASCII characters forming name=value pairs or standalone <name> entries, terminated by a **semicolon** and each entry is separated from the next by a space character as specified in section 7.1 of ST 2110-20-2017."

Nonetheless I am receiving the following in one my tests: "cdi_profile_version=01.00; sampling=YCbCr422; depth=8; **width=1920, height=1080**; exactframerate=30000/1001; colorimetry=BT709;"

Notice how **width** and **height** are separated by a **comma**; not a **semicolon**. 

In the examples provided in the documentation (see link above) these two values (width/height) are separated by semicolon.

![image](https://user-images.githubusercontent.com/55061834/122796294-374d4f80-d28c-11eb-940d-f7aeeca0b0cf.png)

**Comment by yanniel** [comment]
Similarly the Baseline Profile Video Format Specification refers to the values of sampling as "YCbCr-4:2:2", "YCbCr-4:4:4" and "RGB" yet in my tests "YCbCr422" is received (without hyphen or colons).

I am aware of the facilities provided by the SDK to parse and create the baseline profiles, yet I would expect everything to adhere to these "specifications".

**Comment by mhhen** [comment]
Thank you for pointing out this problem. We will update the code and replace the commas with semicolons as described in the "specification" document. There are currently two profiles: v1.00 and v2.00. We will update this issue after the files have been updated and committed.

Concerning the values of sampling, you must be using V1.00 of the protocol. V2.00 uses values like "YCbCr-4:2:2". See the table [here.](https://github.com/aws/aws-cdi-sdk/blob/a0d0cbf499e3c96ce3510810f58ae96bb6350480/src/cdi/baseline_profiles_2_00.c#L51)

You can select the profile version by setting this [value](https://github.com/aws/aws-cdi-sdk/blob/a0d0cbf499e3c96ce3510810f58ae96bb6350480/include/cdi_baseline_profile_01_00_api.h#L98) (use 2 for major and 0 for minor) before using the `CdiAvmMakeBaselineConfiguration() ` function. Please let us know if this does not solve the problem.

**Comment by mhhen** [comment]
The code has been updated in [Release 2.3](https://github.com/aws/aws-cdi-sdk/releases/tag/v2.3.0).
