### ISSUE TITLE
doxygen installation

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#51]
Hi
These makefile lines fail, and were commented out:
docs : $(docs_top_index)
   $(build_doxygen_index)

docs_api_directory := $(product_name)_api_docs_html_$(product_version_name)

docs_api : $(docs_top_index) | $(build_dir.packages)
   $(build_doxygen_index)
   $(Q)tar --transform "s,^,$(docs_api_directory)/," -C $(build_dir.doc)/api/html -zcvf $(build_dir.packages)/$(docs_api_directory).tar.gz .

Please provide instructions how to install doxygen. Does it rqure a specific version?

**Comment by mhhen** [comment]
Avi,

To install Doxygen, use the Doxygen related steps within the install guide sections for [Linux](https://github.com/aws/aws-cdi-sdk/blob/developer_preview/INSTALL_GUIDE_LINUX.md#install-package-dependencies) or [Windows](https://github.com/aws/aws-cdi-sdk/blob/developer_preview/INSTALL_GUIDE_WINDOWS.md#configure-the-ec2-instance). The minimum version of Doxygen required is define in [Doxyfile](https://github.com/aws/aws-cdi-sdk/blob/a0d0cbf499e3c96ce3510810f58ae96bb6350480/doc/Doxyfile#L1) and at the time of this post is version 1.8.5.

**Comment by AviManor** [comment]
root@ip-172-31-0-174:/home/AviManor/aws-cdi-sdk# sudo apt-get install –y build-essential libncurses-dev autoconf automake libtool libnl-3-dev cmake git doxygen libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libncurses5-dev' instead of 'libncurses-dev'
E: Unable to locate package –y
root@ip-172-31-0-174:/home/AviManor/aws-cdi-sdk#

**Comment by AviManor** [comment]
Hi Mike

I failed to follow your instructions. Added the log as a comment in the case, but since the case is closed I don’t know if you can read it.

Regards

Avi Manor | Real time software engineer |TAG Video Systems | IL +972 73 777 0438 | M: +972 54 5680225 | ***@***.*** ***@***.***>  | www.tagvs.com <http://www.tagvs.com/> 

 <http://www.tagvs.com/>

**Comment by mhhen** [comment]
Avi,

To install Doxygen on Ubuntu, use something like this:  `sudo apt-get install doxygen`. Looks like you had a bad hyphen character in your command line for "-y". See in your log: `Unable to locate package –y`. We will leave this ticket open until you have confirmed that Doxygen has been properly installed and working for you.

**Comment by AviManor** [comment]
Hi Mike
I have copy/paste the installation instructions and replaced each hyphen by hand.
The installation was OK, and documentation was created under build/documentation.
Thank you for your help
Avi
