### ISSUE TITLE
CdiLoggerShutdown crash

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#52]
When calling CdiLoggerShutdown() I get these error messages:
[2021-07-18T15:18:57.849790Z] ERROR: List should be empty. Found entry with log method[LogMethodCallback]
TestFullTx.exe: /home/AviManor/aws-cdi-sdk/src/common/src/logger.c:1239: CdiLoggerShutdown: Assertion `false' failed.

Questions:
1. How can I empty the list prior to shutdown?
2. Is there a way to avoid the assert and return a failure status?

**Comment by mhhen** [comment]
1. Under normal conditions, the list of loggers should either be empty of contain only the stdout logger before  CdiLoggerShutdown() is used. Please check to ensure the initialization and log file creation sequences used in your application follow the models in the test applications provided with the SDK. For example [minimal test applications](https://github.com/aws/aws-cdi-sdk/tree/mainline/src/test_minimal).

Optionally, you can pass "true" to the CdiLoggerShutdown(), which forces the list to be emptied without generating an assert. 

2. We use asserts in the SDK to help identify conditions in code that should normally not occur. This aids in debug and development stages of building applications that use the SDK. Hitting an assert will stop execution immediately. Returning a failure status might require several layers of call stack to be unwound before logic acts on the error condition, making it often difficult to determine where the error was originally generated. In some cases, applications might ignore the error condition and the developer won't even realize there was a problem.

Please let us know if you require additional assistance with this issue. If so, please provide additional details such as what loggers you are using and your initialization and teardown sequence of SDK functions used.

**Comment by AviManor** [comment]
Thank you Mike for your clarification.
I am integrating the SDK with our system. We use a single logger that supports all threads in the system, therefore I am using the callback mode.
It was not clear to me how to use the logger correctly, so I copied some code from cdi_test.c
I would appreciate if you could guide me how to setup a single logger that will support all SDK messages especially error messages.
Will the minimal test example will be sufficient?
Do you have a simple logger cook-book?

**Comment by mhhen** [comment]
Avi,

The best examples are in the minimal test applications. See example code in the transmit variant at [CdiLoggerInitialize](https://github.com/aws/aws-cdi-sdk/blob/3f54945f98ff340947a37cfba3fd84625146eef8/src/test_minimal/test_minimal_transmitter.c#L359), [CdiLogMethodData](https://github.com/aws/aws-cdi-sdk/blob/3f54945f98ff340947a37cfba3fd84625146eef8/src/test_minimal/test_minimal_transmitter.c#L387) and [CdiLoggerShutdown](https://github.com/aws/aws-cdi-sdk/blob/3f54945f98ff340947a37cfba3fd84625146eef8/src/test_minimal/test_minimal_transmitter.c#L597).

If you are still unable to resolve, please provide additional details in this issue.

**Comment by AviManor** [comment]
Thank you Mike for your guidance
I have implemented the three steps and it seems to be working fine.
However, I had to pass a pointer of CdiLogMethodData to the connection creation. Is there a way to avoid it?
Avi

**Comment by mhhen** [comment]
Currently CdiLoggerCreateLog() requires a valid pointer to the CdiLogMethodData. However, this could be changed to default to kLogMethodStdout if the value of the pointer is NULL. See current [logic here](https://github.com/aws/aws-cdi-sdk/blob/eba76e328adebf2bfdf2ebdc9d0ef76e074eda29/src/common/src/logger.c#L779) that requires a valid pointer.
