### ISSUE TITLE
Shutdown an adapter

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#53]
I have successfully tried to initialize more than one adapter (on different interfaces with different IP's) with CdiCoreNetworkAdapterInitialize().
The documentation says that CdiCoreShutdown() should be called when done.
As I understand this will shutdown all adapters. Is there a way to close a single adapter?
If yes, can it be opened again?

**Comment by mhhen** [comment]
Avi,

The [developer_preview](https://github.com/aws/aws-cdi-sdk/tree/developer_preview) branch contains a new API called [CdiCoreNetworkAdapterDestroy](https://github.com/aws/aws-cdi-sdk/blob/d94b3af2b7184b84a50251f86cfa2abea2bc7866/include/cdi_core_api.h#L893). It must be used to destroy an adapter. Each call to CdiCoreNetworkAdapterInitialize() must have a matching call to CdiCoreNetworkAdapterDestroy().

The documentation on the developer_preview branch contains: "CdiCoreNetworkAdapterDestroy() must be called before CdiCoreShutdown() but after all connections using the adapter are closed using CdiCoreConnectionDestroy()."

An adapter can be reopened using CdiCoreNetworkAdapterInitialize().
