### ISSUE TITLE
payload_user_data and RX buffer mismatch

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#54]
I am running a TX-RX test.
The transmitter runs a 32 bit payload counter. The value of the counter is placed in the first 4 bytes of the payload.
It is also placed in payload_user_data  and both fields of the PTP.
The RX log shows a mismatch of one payload between these values.
This mismatch does not appear in the TX log.
Please let me know what I am doing wrong.
[RXlog.txt](https://github.com/aws/aws-cdi-sdk/files/6893257/RXlog.txt)
[TXlog.txt](https://github.com/aws/aws-cdi-sdk/files/6893258/TXlog.txt)

**Comment by mhhen** [comment]
I reviewed the log files that you have provided. I am not able to understand exactly what is going wrong. I see this in the RXlog.txt file: `PayloadCtr 1
VideoCtr   0
GoodCtr    0
BadCtr     1
`

If the PTP fields and payload_user_data fields match on TX and RX, then I assume that that is a bug in the application that is causing the payload data to be corrupt. Are you reusing the buffer for each payload? If so, it is possible that the application is modifying the contents of the buffer before the SDK has completed and sent its contents for the previous payload.

Please provide additional details if this still is an issue for you.

**Comment by AviManor** [comment]
Thank you Mike for helping me find my mistake.
The wrong code looks like this:
`1) Loop forever`
`2) Increment PayloadNum`
`3) Fill buffer with PayloadNum`
`4) Sleep remaining time up to next TX`
`5) Send buffer`
`6) End loop`

The buffer is being sent in line 5, and immediately after that the next payload is inserted into it in line 3.
To fix the mistake I have moved line 4 before line 2. I also make sure the TX callback was called without error. (See case  #60)
