### ISSUE TITLE
Unit size calculation for audio

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#55]
The last line of GetAudioUnitSize() says:
    _**// Each audio sample is 3 bytes. Unit size must contain all the bytes of the samples of all the channels.
    *payload_unit_size_ptr = sizeof(uint8_t) * 3 * channel_count;**_

sizeof(uint8_t) * 3 * channel_count = (1 * 3) * channel_count = 3 * channel_count
Unit size is defined as number of bits, not bytes. It looks like the correct calculation should be: (8 * 3) * channel_count

The same applies to GetAncillaryDataUnitSize()
It should be: sizeof(uint32_t) * 8 = 32

**Comment by mhhen** [comment]
Thank you for identifying this issue. We also noticed a similar problem with Ancillary data. We will fix this as part of our next release, which is scheduled for the end of this month. For reference, current logic is at: [Audio data unit size](https://github.com/aws/aws-cdi-sdk/blob/d94b3af2b7184b84a50251f86cfa2abea2bc7866/src/cdi/baseline_profiles_2_00.c#L333) and [Ancillary data unit size](https://github.com/aws/aws-cdi-sdk/blob/d94b3af2b7184b84a50251f86cfa2abea2bc7866/src/cdi/baseline_profiles_2_00.c#L398).

We will leave this ticket open until the updated code has been released.

**Comment by mhhen** [comment]
The code has been updated in [Release 2.3](https://github.com/aws/aws-cdi-sdk/releases/tag/v2.3.0).
