### ISSUE TITLE
Asserts in rxr_cq_insert_addr_from_rts()

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#56]
I have recently stumbled on an assert in rxr_cq_insert_addr_from_rts(), because of a faulty operation in the transmitter.
Is it possible to replace the assert with a return error code?
Assert causes a crash to our process and we need to avoid this crash.

**Comment by mhhen** [comment]
I am assuming you are trying to avoid crashes in a production environment. We recommend using release builds for production, where asserts are compiled out of the code and do not cause segfaults. Asserts are very useful for discovering and helping pinpoint problems in a debug environment, therefore removing them is not recommended. The function you are concerned with is part of libfabric, which is not part of the CDI-SDK and uses a different GitHub project. If you feel the assert should be removed, please refer to that project.
