### ISSUE TITLE
Ubuntu 18_04 : EFA and CDI tests are completely broken if the GUI Desktop is used

### ISSUE THREAD

**Issue by AlexImagineComm** [aws/aws-cdi-sdk#57]
Please find the images and description of the failed cases here: 
[EFA_CDI_test_failed.docx](https://github.com/aws/aws-cdi-sdk/files/6933737/EFA_CDI_test_failed.docx)

I followed the INSTALL_GUIDE_LINUX and created AWS Linux:
![image](https://user-images.githubusercontent.com/75698860/128236449-bfd11ab8-ac88-49b7-b8a6-0366e9c343ef.png)
I installed the EFA, AWS CDI SDK and AWS SDK - it works just fine while I'm using the PUTTY (SSH) console, just terminal (see part 1 a,b in the attached document).
I installed the Ubuntu Desktop (ubuntu-mate-desktop), because our application uses GUI and the Putty Command Line terminal is not enough.  Please see attached document part 2 a.
I open the Remote Desktop Connection (part 2 b) and connect to the same machine.
As you can see from the part 2 c - the EFA test failed (in the same time you can open the same instance from Putty and it works just fine ). I checked the firewall and fi_info - the firewall is disabled and fi_info display results as expected (see 2 b)
I tried to run _cdi_test --adapter **EFA**_ and it fails see 2 d (in the same time it works just fine from Putty).
I tried to run _cdi_test --adapter **SOCKET**_ and it succeeded see part 2 e.

It seems the  Ubuntu Desktop does not allow EFA work properly.
We tested with Mobaxterm and got the same issue - EFA fails.

Can you please suggest which Ubuntu Desktop should I use (our application contains GUI and the Terminal obviously is not enough). Should I use another GUI Desktop for Ubuntu 18_04 ? Should I switch to the Ubuntu 20_04 (if the 18_04 is not supported?) and use another desktop ?
Please provide us with the instructions which Ubuntu GUI Desktop can be used with EFA/CDI.

**Comment by AlexImagineComm** [comment]
Work around :
It was found that if user works under Desktop GUI ONLY **root can run the EFA**
Connect as root:
sudo -i
![image](https://user-images.githubusercontent.com/75698860/128397537-0ae6a687-6ac8-4ca1-a348-3134af2aa5e1.png)
Update the PATH for the root add path to libfabric/build/debug/util
![image](https://user-images.githubusercontent.com/75698860/128397577-1283f4ec-e0e3-41ac-aa4f-9006612a4691.png)
Now change directory to aws-efa-installer and run test again 
![image](https://user-images.githubusercontent.com/75698860/128397628-643ea032-42af-489d-a062-8ca381982e76.png)
as you can see above if I'm connected as root I can run EFA even fro GUI Desktop. If you try to run cdi_test now – it will still fail with invalid credentials:
![image](https://user-images.githubusercontent.com/75698860/128397783-74efc7cf-b478-4b7f-afd7-fdee95423e42.png)
The reason is that the **root** does not have **_aws credentials_** as **ubuntu** has.
COPY ubuntu credentials (**.aws** directory as it is) to the root HOME:
![image](https://user-images.githubusercontent.com/75698860/128397938-47044838-b1d9-4b59-b2d8-0cba5e13c0a0.png)
Now we can run the cdi test AS **ROOT**:
![image](https://user-images.githubusercontent.com/75698860/128397994-72432e27-3591-4482-aaf7-0028a3611d76.png)
![image](https://user-images.githubusercontent.com/75698860/128398022-042167f1-2de9-4ace-b4e9-c7290e0dbf80.png)

The question is what should I do to have the ubuntu or any other user to run the EFA, CDI - please provide additional information how to set up the Linux/Ubuntu user to use the FEA and CDI.

**Comment by mhhen** [comment]
Alex,

We have not tried using a Desktop with Ubuntu, so are not able to provide guidance at this time. I did some searching on-line and was not able to find any useful information. If you are still experiencing this problem, please let us know by updating this issue.

**Comment by AlexImagineComm** [comment]
I still have this problem and I would appreciate if I can get information what security role , what setting should I give to a user in order to run CDI and EFA. Right now it seems **ONLY root** can run the EFA (in ssh and GUI), which is not the best solution.
Our software contains GUI as well and we need to run the CDI from the GUI.
To answer your question - we still waiting for the help on this issue.

**Comment by mhhen** [comment]
Sorry for the late response on this. It was resolved earlier, but wanted to ensure others know the solution too. See README.md note [here](https://github.com/aws/aws-cdi-sdk/blob/developer_preview/README.md#cdi-enabled-application-only-works-when-run-as-root).
