### ISSUE TITLE
Jpeg-XS receive

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#58]
What indicates that RX payload is compressed as Jpeg-XS?

**Comment by mhhen** [comment]
Currently, the AVM layer of the SDK only supports uncompressed video frames. See the current [AVM specification](https://cdi.elemental.com/specs/baseline-video-vxx.yy.html). Adding support for compressed data would require changes to the structures and types in [this header file](https://github.com/aws/aws-cdi-sdk/blob/mainline/include/cdi_baseline_profile_01_00_api.h), which would then require creating a new AVM profile, something like "JPEG-XS profile" and adding a way to communicate profile information to allow negotiation of a compatible profile version. Support for this feature is not planned at this time, so we are closing this ticket. It will be reopened if plans change.
