### ISSUE TITLE
Late TX payload

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#60]
I run a test that sends 10 payloads per second (every 100,000 uSec). Size of each payload is 20,000 bytes.
The log shows:
CDI StatsGatherPayloadStatsFromConnection(471): Connection[127.0.0.1:2000] Stream[] Payload[712] was late by[20059] microseconds. Max[80000]
CDI StatsGatherPayloadStatsFromConnection(471): Connection[127.0.0.1:2000] Stream[] Payload[761] was late by[20059] microseconds. Max[80000]
CDI StatsGatherPayloadStatsFromConnection(471): Connection[127.0.0.1:2000] Stream[] Payload[774] was late by[20059] microseconds. Max[80000]
CDI StatsGatherPayloadStatsFromConnection(471): Connection[127.0.0.1:2000] Stream[] Payload[785] was late by[20059] microseconds. Max[80000]
CDI StatsGatherPayloadStatsFromConnection(471): Connection[127.0.0.1:2000] Stream[] Payload[792] was late by[20064] microseconds. Max[80000]
CDI StatsGatherPayloadStatsFromConnection(471): Connection[127.0.0.1:2000] Stream[] Payload[795] was late by[20063] microseconds. Max[80000]

My statistics show that CdiAvmTxCallback tx_cb_ptr is invoked for all payloads, but cb_data_ptr->core_cb_data.status_code is kCdiStatusOk for all payloads.
I was expecting some of them to show errors. What am I doing wrong?

**Comment by mhhen** [comment]
Avi,

Is your test using the EFA adapter? Locahost or two EC2 instances? You should not be seeing late payloads like that using the EFA adapter.

The current code does not report a late payload as an error. However, the error status [kCdiStatusMaxLatencyExceeded](https://github.com/aws/aws-cdi-sdk/blob/3f54945f98ff340947a37cfba3fd84625146eef8/include/cdi_core_api.h#L202) does exist, but is not being used. We will review this and update this issue as work progresses.

**Comment by AviManor** [comment]
_Q. Is your test using the EFA adapter?_ A. EFA
_Q. Locahost or two EC2 instances?_ A. Both cases

**Comment by mhhen** [comment]
Avi,

You should not be seeing late payloads using the frequency and size that you have specified on the EFA adapter as localhost or between two instances

Are you positive that your test is only transmitting 10 payloads per second at 20,000 bytes per payload using a timeout of 80,000? Can you please add timestamps to your logging and provide a new log?

**Comment by AviManor** [comment]
[RXlog.txt](https://github.com/aws/aws-cdi-sdk/files/7037988/RXlog.txt)
[TXlog.txt](https://github.com/aws/aws-cdi-sdk/files/7037989/TXlog.txt)

**Comment by AviManor** [comment]
Hi Mike
For some reason I am unable to reproduce the problem today. I have tried over two instances, and over local host. Could it be related to some overloading of the server?
In any case I have added the logs as you requested. Please note that the first 100 payloads are fully logged, then only every 10'th payload is logged. Hope the logs will help.
Let me know if you need additional information.
Avi
