### ISSUE TITLE
Interlaced fields in a frame

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#61]
How can we tell which is the first field and which is the second in interlaced mode?
CdiAvmVideoConfig::interlace is set.

**Comment by mhhen** [comment]
Avi,

When using the AVM API and [interlace](https://github.com/aws/aws-cdi-sdk/blob/4a00ff961dea88e98bf7b02c1898c7c3f1dcee34/include/cdi_baseline_profile_01_00_api.h#L107) is set to true, the [AVM specification](https://cdi.elemental.com/specs/baseline-video-vxx.yy.html) describes the order of fields. See under **Payload Format**, **Example 2**, as shown below:

"Unlike in ST 2110-20, both fields of interlaced video are sent in the same payload; the second field's first sample follows immediately after the last byte of the last sample of the first field while honoring padding rules."
