### ISSUE TITLE
Ancillary channel RX high CPU utilization

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#63]
When we open an RX connection for ancillary data, we get a new thread that consumes very high CPU utilization.
Is there a way to reduce that?

**Comment by mhhen** [comment]
An RX connection requires a poll thread. It runs 100% of the time polling for incoming adapter packets. The CDI-SDK 2.3 added support so a single poll thread can be shared and used for multiple connections. Using a single poll thread for all your connections will greater reduce overall CPU utilization.
