### ISSUE TITLE
Statistics callback gets called after connection is destroyed

### ISSUE THREAD

**Issue by AviManor** [aws/aws-cdi-sdk#64]
CdiRxConfigData::stats_cb_ptr gets called after CdiCoreConnectionDestroy() is called
My code in stats_cb_ptr refers to the connection itself, therefore I get a crash.

**Comment by mhhen** [comment]
This problem should have been resolved as part of the v2.4.0 release. Please let us know if the problem still exists.

**Comment by AviManor** [comment]
Tested with Ver. 2.4.1, problem still persists.
Can you please point me to the fix in the code, so I can make sure I am compiling the right version.

**Comment by mhhen** [comment]
I used the cdi_test test application and put a breakpoint after this line:
https://github.com/aws/aws-cdi-sdk/blob/aac4171f2ff8a5e4de24579a4641bb2b6f36e3be/src/cdi/endpoint_manager.c#L755

The stats callback in cdi_test is not called after this line is executed. I can't find any specific code changes related to this issue. Can you please provide some additional details on how you are reproducing?

**Comment by AviManor** [comment]
Hi Mike
Please look at NoCrash.log
Log time tags are in uSec

When I create a connection I attach a magic number to it, to indicate wether the connection is valid or not. See line 13
In line 14 the statistics callback is set to CON_p_StatisticsCallback(). See CON_p_StatisticsCallback.cpp.log
Lines 34 & 51 show two calls to the callback.
Line 73 is the start of connection deletion.
Line 81 is the problem, it should not be executed.
In line 83 the magic number prevents the crash.

YesCrash.log is the same, but line 8 of CON_p_StatisticsCallback() is commented out. Therefore we get a crash at line 86

[YesCrash.log](https://github.com/aws/aws-cdi-sdk/files/10247970/YesCrash.log)
[NoCrash.log](https://github.com/aws/aws-cdi-sdk/files/10247980/NoCrash.log)
[CON_p_StatisticsCallback.cpp.log](https://github.com/aws/aws-cdi-sdk/files/10247989/CON_p_StatisticsCallback.cpp.log)

**Comment by mhhen** [comment]
The stats_user_cb_param holds the value that you supplied to the CDI-SDK when the connection was created. See usage in your callback as shown below:

`Connection_c* CON_ptr = static_cast<Connection_c*>(cb_data_ptr->stats_user_cb_param) `

The memory managed by it is controlled by your application. The stats callback is invoked one last time by the CDI-SDK when the stats thread is shutting down. This is done before the CDI-SDK endpoint is internally destroyed by the CDI-SDK, which holds the stats_user_cb_param. See logic [here](https://github.com/aws/aws-cdi-sdk/blob/86e505eede3e295228b88425c2bfb11f9ff7b85c/src/cdi/statistics.c#L266).

Unless I don't fully understand the problem, it appears that you have marked your endpoint data as destroyed before allowing the CdiCoreConnectionDestroy() to complete and return control to your application. I'm going to close this ticket, but can re-open if needed.
