### ISSUE TITLE
CdiAvmStreamEndpointDestroy hangs unless a connection is successfully established

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#68]
`CdiAvmStreamEndpointDestroy` never exits unless it has previously connected. It hangs waiting for a signal that never triggers in the endpoint manager. Here:

https://github.com/aws/aws-cdi-sdk/blob/808a78e405bafffe772e70794e613b8f501623d9/src/cdi/endpoint_manager.c#L300-L302

This is similar to an issue that existed in v1.0 when destroying connections and was fixed in v2.0 (https://github.com/aws/aws-cdi-sdk/issues/23). It can be a problem if a receiver is unavailable for some reason as it prevents exiting the transmitter. It can be reproduced with the following sequence.

1. CdiCoreInitialize
2. CdiCoreNetworkAdapterInitialize
3. CdiAvmTxStreamConnectionCreate
4. CdiAvmTxStreamEndpointCreate
5. (Wait for the receiver and time out)
6. **CdiAvmStreamEndpointDestroy                            <== HANGS HERE**
7. CdiCoreConnectionDestroy
8. CdiCoreNetworkAdapterDestroy
9. CdiCoreShutdown

Even if a connection is established, it also seems to block in `CdiAvmStreamEndpointDestroy` if the transmitter is shut down without sending any payloads. When this happens, the connection callback fires twice, first with a `kCdiConnectionStatusDisconnected` status followed by a `kCdiConnectionStatusConnected` status. The transmitter then blocks until the receiver exits.

**Comment by JamesMilneFilmlight** [comment]
Plus 1, experiencing the same issue here.

**Comment by mhhen** [comment]
Thank you for providing the detailed steps required to reproduce. We will update the ticket as work progresses on a resolution.

**Comment by mhhen** [comment]
We will be providing a solution in the next release. However, since it can be reduced to a single line change we are providing it here. Just add the line below near [here](https://github.com/aws/aws-cdi-sdk/blob/a8525b08db7c891429e2c5c5a746afeb56ce75bd/src/cdi/endpoint_manager.c#L1119).

`CdiOsSignalSet(EndpointManagerGetNotificationSignal(mgr_ptr));`

**Comment by mhhen** [comment]
The Release v2.4.0 contains the change.
