### ISSUE TITLE
CdiPoolGetBulk and CdiPoolPutBulk implementation is incomplete 

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#69]
It seems that `CdiPoolGetBulk` and `CdiPoolPutBulk` haven't been fully implemented. I don't particularly need these functions but I'm developing a managed .NET wrapper around the CDI SDK and they are currently documented as part of the public API. Are they supported?

https://github.com/aws/aws-cdi-sdk/blob/808a78e405bafffe772e70794e613b8f501623d9/src/common/src/pool.c#L472-L483

https://github.com/aws/aws-cdi-sdk/blob/808a78e405bafffe772e70794e613b8f501623d9/src/common/src/pool.c#L485-L496

**Comment by mhhen** [comment]
Thank you for identifying that. You are correct, the implementation for those APIs was never started. We will plan on removing the APIs and the stub code as part of our next release. We will close this issue after the change has been made available.

**Comment by f2bo** [comment]
Good. Less code to write :smile:. Thanks!

**Comment by mhhen** [comment]
The change has been made available on the [developer_preview](https://github.com/aws/aws-cdi-sdk/tree/developer_preview) branch.
