### ISSUE TITLE
Example video file not compatible with video test command line? 

### ISSUE THREAD

**Issue by peterbrightwell** [aws/aws-cdi-sdk#7]
https://github.com/aws/aws-cdi-sdk/blob/mainline/USER_GUIDE_TEST_APP.md#example-test-content suggests using examples from https://cdi.elemental.com/test_content. However Color_Bars_1080P_422_8bit.yuv is only 4147200 bytes but example in https://github.com/aws/aws-cdi-sdk/blob/mainline/USER_GUIDE_TEST_APP.md#video-test-with-input-file requires a 5184000 (10 bit) file.

**Comment by rssjonaaws** [comment]
Hello Peter, thank you for reaching out and notifying us of the discrepancy in the [User Guide](https://github.com/aws/aws-cdi-sdk/blob/mainline/USER_GUIDE_TEST_APP.md#video-test-with-input-file) concerning the 10bit command-line test file example versus the [provided test content](https://cdi.elemental.com/test_content/index.html). This can be resolved by using an 8bit command-line option with the following parameters: --payload_size **4147000**, --avm_video 1920 1080 YCbCr422 Unused **8bit** 60 1 BT2020 true false PQ Narrow 16 9 0 1080 0 0.

We will address this issue by uploading a 10-bit file and will subsequently notify you by updating the ticket. Once again, thank you for bringing attention to this issue.

**Comment by trevorheaws** [comment]
We have added the image Color_Bars_1080P_422_10bit.yuv to https://cdi.elemental.com/test_content with an image size of 5184000 bytes to match our user guide examples. Thank you for your patience on this issue.
