### ISSUE TITLE
kCdiStatusMaxLatencyExceeded not used ?

### ISSUE THREAD

**Issue by alistairparker** [aws/aws-cdi-sdk#70]
I notice that cdi_core_api.h defines a number of error response status cods including kCdiStatusMaxLatencyExceeded.
However there is no where in the sdk that this is used except to map it to a string.
Is this a work-in-progress within the SDK or is intended to be set and managed by the application ?

**Comment by ralfjuen** [comment]
Thanks for the question. In general status codes may become unused. This could happen, for example, when an SDK release introduces new, more specific status codes. When a status code becomes unused we do not remove it to avoid the risk that removal may break an application.

In this particular case we intend to make use of status code kCdiStatusMaxLatencyExceeded in a future release, see [this issue](https://github.com/aws/aws-cdi-sdk/issues/60).
