### ISSUE TITLE
CdiQueuePushWaitMultiple always returns true

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#76]
It seems that `CdiQueuePushWaitMultiple` returns **true** regardless of the outcome. If `CdiQueuePush` fails, the loop that waits for a signal is never entered and the function returns the value of `ret`, which was initialized as **true** at the beginning of the function.

https://github.com/aws/aws-cdi-sdk/blob/eba76e328adebf2bfdf2ebdc9d0ef76e074eda29/src/common/src/queue.c#L505-L512

It should probably be:
```C
 while (ret && !CdiQueuePush(handle, item_ptr)) { 
    ...
 }
```

Also, there's a minor error in the documentation for the return value of the function.
https://github.com/aws/aws-cdi-sdk/blob/57ce52b0dfd68a6d2bea3a9e397886c801c28b08/include/cdi_queue_api.h#L166

I assume "true if successful, otherwise false (queue is **full** and timeout expired or signal got set)" is meant.

**Comment by mhhen** [comment]
Thank you for finding and identifying this problem. We will investigate and then update this issue when the changes required have been made available.

**Comment by mhhen** [comment]
The changes for this problem and a preview of the upcoming SDK Release 2.4.1 have been pushed to the [developer_preview](https://github.com/aws/aws-cdi-sdk/tree/developer_preview) branch.

Specific changes for this issue are in [cdi_queue_api.h](https://github.com/aws/aws-cdi-sdk/commit/35c04a71b0b3840f5f81b62909df4967974b6c01#diff-bf4ffea87aecd182e833c769df90148450b660dbcadb37af58ad007a16082085) and [queue.c](https://github.com/aws/aws-cdi-sdk/commit/35c04a71b0b3840f5f81b62909df4967974b6c01#diff-4bdd8e973e9949c6b584838470eeea8a343cd7f8510f2e474e4cc22ed545f495).

**Comment by f2bo** [comment]
Thanks!
