### ISSUE TITLE
Files under aws-cpp-sdk-cdi have apache license

### ISSUE THREAD

**Issue by fivebats** [aws/aws-cdi-sdk#8]
OK, not the biggest deal, but the files in the tree under `aws-cpp-sdk-cdi` contain comments marked with the Apache 2 license, not the BSD-2-Clause license that appears in the top of tree.

(And the statements in those files that I read contain copyright dates that extend only to 2017.)

**Comment by fivebats** [comment]
As a further observation, the remaining source files do not appear to include any license information:

```
// ---------------------------------------------------------------------------
// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// ---------------------------------------------------------------------------
```

Note that by comparison, the files in the standard AWS SDK release have headers that look like this:

```
/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */
```

**Comment by trevorheaws** [comment]
Hi Mike,
 
Thank you bringing this to our attention. We are reviewing our options internally for resolving this license disparity.

**Comment by mhhen** [comment]
Mike,

The files marked with Apache 2 are outputs from the AWS SDK, which is distributed under that separate license. AWS’ other content in the AWS CDI SDK is licensed under BSD-2-clause.

**Comment by fivebats** [comment]
What about the second point? I think it would be useful if you can add the license information to each source file.

As a former AWS employee, it concerns me to have files on my systems that are marked as "Copyright Amazon.com Inc. or its affiliates. All Rights Reserved." with no further licensing information in them, even if some other file somewhere gives me permission.

**Comment by mhhen** [comment]
Mike,

Concerning your second point, although not required by the BSD 2 license, we will add text to the header of each source file that contains something like:

```
The contents of this file is licensed under the BSD 2-Clause "Simplified" License.
For details see: https://github.com/aws/aws-cdi-sdk/blob/mainline/LICENSE
```
