### ISSUE TITLE
Build errors in mainline branch for v2.4.1 (bad merge?)

### ISSUE THREAD

**Issue by f2bo** [aws/aws-cdi-sdk#88]
I see multiple errors when building from the latest `mainline` branch after the recent update. These errors were not present in `developer_preview`, which builds successfully. 

![image](https://user-images.githubusercontent.com/1148767/201352932-a088adc2-81ab-4cca-855d-a44c0f6e5934.png)

It would seem that there was a problem when merging branches. For example:

**developer_preview**
https://github.com/aws/aws-cdi-sdk/blob/34a6027c9033b9c6cb93bcb88c9558ca594f1350/src/cdi/adapter_efa_probe.c#L207

**mainline**
https://github.com/aws/aws-cdi-sdk/blob/aac4171f2ff8a5e4de24579a4641bb2b6f36e3be/src/cdi/adapter_efa_probe.c#L207

or a duplicate `kProbeCommandProtocolVersion` case here:
https://github.com/aws/aws-cdi-sdk/blob/aac4171f2ff8a5e4de24579a4641bb2b6f36e3be/src/cdi/adapter_efa_probe_rx.c#L289-L310

**Comment by mhhen** [comment]
Thank you for identifying this problem. You are correct concerning the merge from the developer_preview branch. A few files did not merge correctly. The changes have been made and the 2.4.1 release has been revised.
