### ISSUE TITLE
Krill name appears in some files

### ISSUE THREAD

**Issue by fivebats** [aws/aws-cdi-sdk#9]
You may want to review the files to remove what appears to be a leaked code name.

'krill' appears in at least these places:

- aws-cpp-sdk-cdi/include/aws/cdi/model/PutMetricGroupsRequest.h
- doc/rx_reorder_sglist.png

I did not do an exhaustive search.

**Comment by trevorheaws** [comment]
Thank you for taking the time to provide us with this feedback. We are reviewing the information you provided and will update this issue with progress accordingly.

**Comment by trevorheaws** [comment]
We are marking this issue resolved. Please reopen the issue if you see something that would require further action.
