### ISSUE TITLE
Linux install guide should include adding mediaconnect:PutMetricGroups policy

### ISSUE THREAD

**Issue by t11s** [aws/aws-cdi-sdk#93]
As the mediaconnect:PutMetricGroups policy needs to be added to the IAM user to run cdi_test_min_rx, perhaps the Linux install guide should mention adding this policy when the CloudWatch policies are added.

**Comment by mhhen** [comment]
Thank you for providing this information. There was some existing notes in the README.md file, but we will also add this into the Linux install guide as well. The change has been pushed to the developer_preview branch. See change [here](https://github.com/aws/aws-cdi-sdk/commit/c2f2d92a5fbcd2170ee42e06ee85963b93e357b1).
