### ISSUE TITLE
CdiCoreInitialize deinitializes the SDK when called an even number of times

### ISSUE THREAD

**Issue by MathieuDuponchelle** [aws/aws-cdi-sdk#94]
After https://github.com/aws/aws-cdi-sdk/issues/34 was solved, the logic in `src/cdi/internal.c` essentially amounts to:

```
sdk_initialized = false;

CleanupGlobalResources { sdk_initialized = false; }

InitializeSdk  {
  rs = Ok;

  if sdk_initialized {
     LOG ("Already initialized");
    rs = NotFatal;
  }

  if (rs == Ok) {
    sdk_initialized = true;
  } else {
    CleanupGlobalResources();
  }

  return rs;
}
```

Is that the intended behaviour ?

**Comment by mhhen** [comment]
This is not the correct behavior. Have fixed the problem and pushed the change to the developer_preview branch. See change [here](https://github.com/aws/aws-cdi-sdk/commit/d007ff3992e53784a2b415823114fa4a48bc0a42)
