### ISSUE TITLE
Question: what is the purpose of kCdiStatusAdapterDuplicateEntry ?

### ISSUE THREAD

**Issue by MathieuDuponchelle** [aws/aws-cdi-sdk#95]
Two processes can successfully instantiate an adapter for the same IP address, why isn't it possible within a single process?

**Comment by mhhen** [comment]
Creating multiple instances of the same adapter within a single process doesn't make sense due to the additional resources required such as a poll thread, standard memory for buffers and huge page memory for adapter level packet buffers. Multiple connections can be established using a single adapter. See comments and logic in the CDI-SDK code [here](https://github.com/aws/aws-cdi-sdk/blob/eba76e328adebf2bfdf2ebdc9d0ef76e074eda29/src/cdi/internal.c#L424).

Please let us know if there is a specific need or reason to use multiple instances of the same adapter within a single process.

**Comment by MathieuDuponchelle** [comment]
Hey @mhhen I have implemented simple GStreamer wrappers around this API, and in trying to make them as flexible as possible this was a clear issue I encountered.

Basically, GStreamer can be used in a very dynamic way, adding and removing sink (~ exit nodes) elements during the whole lifecycle of a process, and the size of the adapter to request isn't known in advance, let's take a simple example:

You start by creating a connection with one video endpoint, and reserve an adapter with space for one frame for the format that gets negotiated (depending on resolution / pixel format / etc ..).

Streaming starts, then after a while you want to add a new video endpoint with an entirely different format, for the sake of discussion let's say frames for that stream are actually larger.

How do you recommend I solve this problem in a simple and generic way?

**Comment by MathieuDuponchelle** [comment]
ping @mhhen :)

**Comment by mhhen** [comment]
If you don't want to interrupt the existing flow, you need to reserve enough memory to hold the largest frame format that you need to dynamically support. The only other option is to tear-down the existing endpoint and related adapter and recreate using the new required buffer size.

**Comment by MathieuDuponchelle** [comment]
Right, that is the specific need I have to use multiple instances of an adapter within a single process, I don't want to interrupt data flow and I can't know the "largest frame format I need to support" in advance, by definition, as I am writing generic elements for other applications to make use of.

Besides, sharing the adapter space for a single frame between multiple sink elements (~ endpoints) isn't exactly ideal, in the future I would like to implement buffer pools, but then again one adapter per sink would make things much much easier.

**Comment by MathieuDuponchelle** [comment]
I still think this should probably be re-opened, the code you linked to doesn't actually explain the rationale behind the limitation @mhhen :)
